name: Android Build

on:
  push:
    branches:
      - main

jobs:
  signed:
    name: build signed APK
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: sudo apt-get -y update
        shell: bash

      - run: sudo apt-get -y install openjdk-11-jdk
        shell: bash

      - shell: bash
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > $GITHUB_WORKSPACE/upload-keystore.jks

      - name: Build Signed APK
        run: |
          echo "KEYSTORE_PATH=$GITHUB_WORKSPACE/upload-keystore.jks" > release.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> release.properties
          echo "STORE_PASSWORD=${{secrets.STORE_PASSWORD}}" >> release.properties
          echo "ALIAS=${{ secrets.ALIAS }}" >> release.properties

      - name: build release
        run: ./gradlew app:bundleRelease
#      - name: build release
#        run: ./gradlew assembleRelease

      - name: remove keystore.jks
        shell: bash
        run: rm $GITHUB_WORKSPACE/upload-keystore.jks

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.jshvarts.flows
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: alpha
          whatsNewDirectory: distribution/

#      - name: upload artifact to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{ secrets.FIREBASE_APP_ID_PROD }}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: testers
#          file: app/build/outputs/apk/release/app-release.apk
